"""
Django settings for BabluPrintingPress project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+os4#=5onpvp^o9kz29&=6wlax!#32u=&gcs%6_$l!o7@lrmhk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'BabluPrintingPress',
    'catalog',
    'user',
    'django_browser_reload',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
]

ROOT_URLCONF = 'BabluPrintingPress.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'BabluPrintingPress' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BabluPrintingPress.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'BabluPrintingPress' / 'static']
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


JAZZMIN_SETTINGS = {
    "site_title": "Bablu Printing Press Admin",
    "site_header": "Bablu Printing Press",
    "site_brand": "Bablu Printing Press",
    "site_logo": "logo.png",   # must be in static folder
    "login_logo": "logo.png",
    "welcome_sign": "Welcome to Bablu Printing Press Admin",
    "copyright": "Bablu Printing Press",
    "custom_css": "css/admin.css",
    "search_model": ["catalog.Product", "catalog.Category"],

    "topmenu_links": [
        {"name": "View Site", "url": "/", "new_window": True},
    ],

    "icons": {
        "auth": "fas fa-users",
        "auth.user": "fas fa-user",
        "catalog.category": "fas fa-layer-group",
        "catalog.product": "fas fa-box",
        "catalog.productimage": "fas fa-image",
        "catalog.productvideo": "fas fa-video-camera",
    },

    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file",

    "show_sidebar": True,
    "navigation_expanded": True,

    "theme": "lumen", 
}
