# Generated by Django 6.0 on 2025-12-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productimage_image_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_note',
            field=models.CharField(blank=True, help_text="e.g. 'Starting from', 'Approx price', 'Per 100 cards'", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Starting price (e.g. 1500.00)', max_digits=10, null=True),
        ),
    ]
